### ISSUE TITLE
[Tooling] Quizzes direkt im Skript?

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/PM-Lecture#332]
Gibt es JavaScript-Lösungen oder andere Lösungen, so dass man die Quizzes direkt in die Vorlesungsskripte einbetten kann? Die Lösungen müssten in der Webseite codiert sein und über ein Javascript müsste die eingegebene Lösung gegen die Vorgabe geprüft und eine Rückmeldung angezeigt werden.

Was ist mit ["Ankhi"-Cards](https://apps.ankiweb.net/)? **Was ist mit https://github.com/bonartm/hugo-quiz und https://github.com/bonartm/quizdown-js?**

**Edit: Alternativ könnten die Quizzes direkt in die Lecture-Seiten eingebunden werden: https://github.com/bonartm/hugo-quiz (siehe https://github.com/McShelby/hugo-theme-relearn/issues/507)**

siehe auch https://github.com/Programmiermethoden/PM-Lecture/issues/331

siehe auch https://github.com/KI-Vorlesung/Lecture/issues/145

**Comment by AMatutat** [comment]
Verständnisfrage: Willst du die Kahoots einbinden (also direkt von der Webseite) oder "nur" die Quzizzes?

**Comment by cagix** [comment]
> Verständnisfrage: Willst du die Kahoots einbinden (also direkt von der Webseite) oder "nur" die Quzizzes?

Guter Einwand. Früher habe ich in die Skripte einen Link auf die Kahoots eingebettet. Das habe ich durch einen Link auf die ILIAS-Quizzes ersetzt, weil die Kahoots ja leider nur eine begrenzte Lebensdauer haben und irgendwann zugehen.

Was ich suche:
- Einbetten des Quiz als Markdown (+ Code, + Bildchen, ...) direkt in das Vorlesungs-Markdown
- Anzeigen der Fragen in der Vorlesungswebseite 
- Rückmeldung, ob die Antwort korrekt war direkt auf der Vorlesungswebsseite (per Skript)

Dadurch wären die Quizzes eng an die Vorlesung gekoppelt (sie stehen ja in den VL-Materialien direkt drin), man kann eine Verbesserung/Überarbeitung/Korrektur quasi nicht vergessen. Und wir bräuchten nicht externe Lösungen wie Kahoot oder ILIAS, wo man wieder was einrichten und dorthin verlinken muss.

**Comment by jedi101** [comment]
Fänd ich meget godt! Wenn das da irgendwann eingebaut ist belege ich PM einfach noch mal!

**Comment by cagix** [comment]
> Fänd ich meget godt! Wenn das da irgendwann eingebaut ist belege ich PM einfach noch mal!

@jedi101 musst du nicht irgendwann auch noch ne bachelorarbeit schreiben? 😎🤔

**Comment by cagix** [comment]
> Am besten wäre, wenn man markdown schreiben könnte und pandoc/hugo dann draus ein eigenes javascript kahoot system raus basteln würden.

das ist die idee. wir schreiben markdown, und beim konvertieren wird eine javascript-lib dazugepackt (hugo) und von mir aus wird das markdown noch bearbeitet (pandoc) und voila :)

**Comment by cagix** [comment]
=> https://github.com/cagix/pandoc-lecture/issues/179
