### ISSUE TITLE
ILIAS: Etherpad einrichten

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/PM-Lecture#351]
- Slot-Wahl im Praktikum, zusätzlich mit Online vs. Präsenz

**Comment by AMatutat** [comment]
soll ich dir das abnehmen?

**Comment by cagix** [comment]
gern: 

- slots alle halbe stunde, im prinzip sollten wir 3 teams parallel abnehmen können. 
- für jedes team "vorname name, vorname name, vorname name" und "präsenz" oder "hybrid"

**Comment by AMatutat** [comment]
@cagix stimmen die Zeiten auf den Stundenplan? 
G1: 9:00-10:30
G2: 10:45-12.15
G3: 13:15-14:45

**Comment by cagix** [comment]
> @cagix stimmen die Zeiten auf den Stundenplan?
> G1: 9:00-10:30
> G3: 10:45-12.15
> G2: 13:15-14:45

vermutlich nicht, da gab es änderungen. in https://github.com/PM-Dungeon/PM-Lecture/blob/master/markdown/_index.md sollten die richtigen zeiten stehen :)

**Comment by AMatutat** [comment]
@cagix 
Review (oderso): https://www.fh-bielefeld.de/elearning/ilias.php?ref_id=1047986&cmdClass=ilrepositorygui&cmdNode=wr&baseClass=ilrepositorygui

**Comment by cagix** [comment]
> @cagix Review (oderso): https://www.fh-bielefeld.de/elearning/ilias.php?ref_id=1047986&cmdClass=ilrepositorygui&cmdNode=wr&baseClass=ilrepositorygui
> 

danke. schaue ich mir bei gelegenheit an.

> Ich habe keine explizite Lüftungspause eingeplant.

gibt ja auch kein corona mehr, schutzmaßnahmen sind komplett überflüssig und spanien(?) hat corona zu einer normalen grippe erklärt. /s  ... könnte ins essen brechen über die dummheit der leute. 🤮

**Comment by jedi101** [comment]
...meanwhile, in a small foreign country named China... 👀

**Comment by cagix** [comment]
@AMatutat Jetzt hast Du für Gruppe 2 doch die alte Zeit genommen?

**Comment by AMatutat** [comment]
> @AMatutat Jetzt hast Du für Gruppe 2 doch die alte Zeit genommen?

argh....da hat sich irgendwas überschnitten 

> hab g2 nochmal schnell angepasst. danke für die vorarbeit!

super , danke
