### ISSUE TITLE
[D2A] Workflow der Studierenden definieren

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/PM-Lecture#566]
Um eine passende Toolchain zu bauen, sollten wir einen konkreten Workflow für die Abgabe von Lösungen definieren.

Wo liegen die Vorgaben? Wo liegen die Tests? Wie wird Abgegeben?

**Comment by AMatutat** [comment]
@cagix Habe jetzt erstmal nur die Übergreifenden Issues transferiert. Also alles was nicht konkret ausprobiert werden kann.

**Comment by AMatutat** [comment]
Die Vorgaben bereitstellen ist eine Sache, aber die Abgabe durchführen eine andere.

Aktuell forken sich die Studierenden das Vorgabe-Repo und lösen die Aufgaben in Branches. Abgabe findet dann per Pull-Request im eigenen Repo statt. 
Für eine automatische Bewertung der Abgabe ist mir  das aber zu "riskant". Ich würde den Studierenden ungerne Zugriff auf die Technik geben, die ihre Note mitbestimmt. 
Daher schlage ich ein Abgabe-Repo vor. Ob `Vorgabe-Repo == Abgabge-Repo` müsste man dann prüfen, wenn die Technik da ist.

Das nächste Problem sehe ich in den Inhalten der Toolchain. Die GitHub Actions, die in einem PR laufen, nutzen die Tests und Konfigurationen des Quell-Branches nicht des Target-Branches. Ich könnte also die Tests und Metriken manipulieren. 
Wir sollen mal schauen, ob das auch anders geht #570. 


Der (für mich) optimale Workflow für die Studierenden sieht für mich daher so aus:
1. Forken des Vorgabe Repos
2. Erstellen eines Branches im Fork um ein Task zu lösen
3. PR in den Master des Forks
    - Hier kann die Toolchain schonmal eine Trockenübung durchführen, die Studierenden sehen also, wo es ggf. noch Probleme gibt.
4. Mergen
5. PR vom Master in das Abgabe Repo

Daraus ergibt sich dann noch #571.

**Comment by AMatutat** [comment]
@cagix 

Ich habe grade einen Gedanken zu der Art und Weise gehabt, in welcher Struktur wir die Vorgaben bereitstellen. 
Aktuell sieht die Struktur so aus:
```
task1
  /src
  /test
task2
  /src
  /test
...
```
jeder Task ist daher (sowas wie) ein eigenes Projekt.

Eine Alternative wäre es, alles als ein Projekt "Konzeptaufgaben"  zu verstehen. Die einzelnen Task sind dann packages (ggf. mit sub-packages). 

```
src
  /task1
  /task2
test
  /task1
  /task2
```
Nachteil: Die Idee mit einem Build-Skript für jedes Task wäre nicht mehr so einfach umsetzbar. 

Vorteil: Der Workflow ist für die Studierenden angenehmer, die müssen sich nur einmal ein Projekt anlegen und das nicht jede Woche wiederholen. Für uns wird das Handling innerhalb der Toolchain einfacher, da wir nicht mehr über mehrere sub-folder iterieren müssen.

**Comment by cagix** [comment]
Ich war früher ein großer Anhänger des "Ein Projekt, mehrere Packages"-Konzepts. Wie Du schreibst, muss man in der IDE nur ein Projekt anlegen und über die Packages kann man die Aufgaben gut unterscheiden. 

Aber andererseits hast Du das Problem, wenn Du eine Aufgabe nicht richtig hinkriegst, dann kompiliert alles nicht mehr - Du schleppst die alten Probleme immer mit Dir rum in der IDE (sind ja nur Packages von _einem_ Projekt). Da wäre es besser, für jeden Task ein neues Projekt aufzumachen (eigentlich sogar ein eigenes Repo, aber das führt dann doch zu weit).

Für uns lässt die Variante mit dem "ein Task == ein Projekt"-Konzept mehr Freiheiten: Jeder Task/jedes Projekt bekommt sein eigenes Build-Skript und man könnte darüber dann genau steuern, was in dieser Aufgabe alles erledigt werden soll. Allerdings muss ich dann darüber eine Art Master-Buildskript haben, was über die Projekte iteriert und die dortigen Build-Skripts anstößt und die Daten zusammensammeln lässt.

**Comment by AMatutat** [comment]
> Du schleppst die alten Probleme immer mit Dir rum

Kritischer Punkt. Hab ich nicht drüber nachgedacht.

**Comment by AMatutat** [comment]
Mittlerweile haben wir einen Workflow definiert:

Aus Sicht der Studis:
Diese bekommen zwei private Repos vorgegeben. Eines für das Dungeon und eines für die Konzeptaufgaben.

Ihre Konzeptaufgaben lösen die Studierenden und mergen die Lösung dann in Ihren Master. Die Bewertung findet bei uns lokal (vermutlich am Ende des Semester statt). Es werden nur Commits berücksichtigt, die in der jeweiligen Deadline liegen. Nur Studierenden die mindestens einen Commit für die jeweilige Lösung eines Task gemacht haben, bekommen Punkte.
Für die Transparenz geben wir den Studierenden unser Skript mit, diese können also selbst prüfen, wie viele Punkte sie bekommen und wer alles Punkte bekommt.
Die Studierenden arbeiten nur im `$task_name/loesung` Ordner, alle anderen Änderungen werde nicht mit berücksichtigt.
Die Studierenden sind selbst für die fristgerechte Abgabe (es zählt nur was im master liegt) und das einhalten der Kriterien zuständig.

Ihren Fortschritt im Dungeon stellen die Studierenden wie gewohnt im Praktikum vor. Hier gibt es den großteil der Punkte.
In regelmäßigen Abständen wird auch im Dungeon eine automatische Kontrolle zum überprüfen der Codequalität durchgeführt.
