### ISSUE TITLE
[D2A] Datenschutz

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/PM-Lecture#567]
Da die Ergebnisse der Toolchain einen Teil der Note ausmachen, müssen wir auf den Datenschutz achten. 

Welche Datenschutzrechtlichen Bedenken gibt es? Was müssen wir beachten? Wie gehen wir damit um?

**Comment by AMatutat** [comment]
@cagix Da wir lokal arbeiten und die Studis in Privaten Repos, sollte dieser Punkt eigentlich hinfällig sein, oder?

**Comment by cagix** [comment]
ja, sehe ich auch so.

die studis arbeiten zudem auf wunsch mit irgendwelchen pseudonymen. und zur not eben auch im gitlab ...
