### ISSUE TITLE
[D2A] CI Konfiguration nur aus dem Master

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/PM-Lecture#570]
Um Manipulation der Unit-Tests und Metrik-Konfiguration bei einer Abgabe per Pull Request auszuschließen, müssen die Actions so konfiguriert sein, dass die Unit-Tests und Metrik-Konfiguration immer aus dem Target-Branch genommen werden.
So behalten wir die Kontrolle darüber, mit welchen Mittel geprüft wird.

**Comment by cagix** [comment]
Alternativ könnte man überlegen, dass bestimmte Branches in einen Hilfsordner ausgecheckt werden ([git worktree](https://git-scm.com/docs/git-worktree)) und per `diff` mit den Inhalten des Studi-Branches verglichen werden. Bei Nichtgefallen wird der Build/Test abgebrochen.

**Comment by AMatutat** [comment]
Random Gendanke und ich weiß grade nicht so 100% wohin damit:
Die Abgaben haben eine Deadline. Wenn die Toolchain diese Deadline beachten könnte (Konfigurationsfile) und nach Ende der Deadline keine PRs mehr abarbeitet, hätten wir weniger Management-aufwand.

**Comment by AMatutat** [comment]
> Alternativ könnte man überlegen, dass bestimmte Branches in einen Hilfsordner ausgecheckt werden ([git worktree](https://git-scm.com/docs/git-worktree)) und per diff mit den Inhalten des Studi-Branches verglichen werden. Bei Nichtgefallen wird der Build/Test abgebrochen.

Vielleicht ein eigener Docker? Da wären wir wohl am freisten in der Gestaltung und könnten uns von externen Abhängigkeiten lösen. Man müsste nur schauen, wie man den spezifischen PR im Container auschecked und wie man die Ergebnisse wieder nach GitHub kriegt.

**Comment by AMatutat** [comment]
> allerdings steht dieses "ziehe image xyz" ja auch wieder irgendwo, und die studis könnten das umbiegen.

Stimmt auch wieder. Schiebt das Problem nur von einem Ort an den anderen.

**Comment by cagix** [comment]
> > allerdings steht dieses "ziehe image xyz" ja auch wieder irgendwo, und die studis könnten das umbiegen.
> 
> Stimmt auch wieder. Schiebt das Problem nur von einem Ort an den anderen.

es wird halt immer komplexer, was die wahrscheinlichkeit von ungewollten änderungen reduziert (aber eben nicht auf null runterbiegt). andererseits wird auch die konfiguration auf unserer seite immer komplexer ...

**Comment by AMatutat** [comment]
Mit dem geplanten Vorhaben umgehen wir die Probleme einer ungewollten oder böswilligen Manipulation der vorgaben.
