### ISSUE TITLE
[D2A] Alternative zu GitHub-Actions

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/PM-Lecture#572]
In den meisten Diskussionen über D2A sind wir davon ausgegangen, dass wir die Workflows von Git (GitHub-Action) nutzen.

Ist das wirklich der beste Weg? Gibt es alternativen Weg? 

Die Actions haben den Vorteil, dass sie "ein Teil von Git" sind und gut in den tatsächlichen Git-Workflow eingebunden werden können. Außerdem müssen wir nicht aktiv einen anderen Dienst pflegen. Uns werden dadurch aber auch Spielregeln aufgezwungen, die zwar für normales Arbeiten sinnvoll sind, aber uns einschränken bzw. blockieren. Hier müssen wir dann eklige Umwege finden oder unsere Anforderungen runterschrauben.

**Comment by AMatutat** [comment]
Eine Alternative könnte ein, auf unserm Server laufendes, Skript sein.

Dem Skript würde eine Liste mit den Studi-Repos gegeben werden und eine Konfigurationsdatei, in der steht, welche Tasks zu welchem Zeitpunkt abgegeben worden sein müssen.

Das Skript zieht sich dann den letzten Stand des Masters der Studi-Repos vor dem Abgabezeitpunkt und führt die Tests/Toolchain für die entsprechenden Tasks aus und sammelt die Ergebnisse ein. 
Die Tests und die Konfiguration der anderen Tools holt sich das Skript von unserem Vorgabe-Repo. 

Ergebnisse könnten dann direkt auf dem Server gespeichert werden. Für jeden Studi eine Tabelle. Da müssen wir dann natürlich ordentlich Backups machen.  

Die Ergebnisse könnte man den Studis dann auch vom Server per Mail zuschicken lassen.

**Comment by cagix** [comment]
Das ist ein interessanter Gedanke!

Ich würde das leicht modifizieren: Die Studis kriegen über die Vorgaben Testsuiten und GH-Workflows mit in ihr privates Repo. Die Lösung wird über einen PR im eigenen Repo abgegeben, und die Studis kriegen quasi fortlaufend Feedback über die CI.

Wir haben ein Skript (Python, Make, ...), wo die Repos konfiguriert sind und welches sich offene PRs mit bestimmten Merkmalen runterzieht und lokal auf dem Rechner des Dozenten ausführt. Dann kann dort auch gleich noch eine Gesamtliste erstellt werden etc. und wir haben keine Probleme mit Datenschutz und so ... 

Ein wenig sträubt sich alles gegen "ein Skript auf meinem Rechner", aber letztlich könnte man das auch in einem privaten Repo auf der CI laufen lassen (nur dann ohne die Gesamttabelle). Hmmm.

**Comment by cagix** [comment]
> Für Python könnte `gitpy` eine gute Möglichkeit sein, um die Inhalte von Git zu kriegen. 
> 
> Dann per shell Befehl aus dem Python Skript die Gradle-Targets ausführen, Ergebnisse sammeln und speichern, aufräumen und zum nächsten Repo. 

aber dann kann man das doch gleich per make machen

**Comment by AMatutat** [comment]
> aber dann kann man das doch gleich per make machen 

Make anstelle von Gradle? Ja, aber wieso? Make anstelle von Python? Sehe ich ehr nicht so. Python gibt dir bessere Möglichkeiten mit den Daten umzugehen, die zu formatieren etc.

**Comment by cagix** [comment]
- pull, checkout: das ist einfacher und verlässlicher direkt im shell-script oder makefile
- compilieren, junit, checkstyle, metriken: gradle (oder maven)
- diffs, ...: shell
- zusammensammeln, tabelle erstellen: whateverfloatsyourboat ... 

der gesamtablauf darf aber gern durch ein shell-skript oder makefile orchestriert werden. da sehe ich nicht python.

**Comment by AMatutat** [comment]
Ich weiß nicht, ob das auschecken von Pull Requests per Shell wirklich einfacher ist. Immerhin müssen wir auch Randbedingungen checken. Welchen pr checken wir aus? Was sollte da drinne sein? Ist der Zeitrahmen eingehalten? 

Autorisierung des Skripts per Git-Token für die einzelnen Repos muss auch gewährleistet sein.

**Comment by AMatutat** [comment]
Dieses Ticket war als Diskussion gedacht und wir haben uns nun für das Python-Skript entschieden. Dieses kann sowohl on der Action als auch lokal ausgeführt werden.
