### ISSUE TITLE
[GIT] .gitignore und .gitattributes anpassen, .editorconfig überprüfen

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/PM-Lecture#595]
- [x] `.gitattributes`:
  ```
  * text=auto eol=lf

  *.cmd text eol=crlf
  *.bat text eol=crlf
  ```
- [x] `.gitignore`: für die im Repo tatsächlich betrachteten Dateien formulieren, nicht allgemein für "alles"
- [x] `.editorconfig`: nochmal überprüfen, ob das alles Sinn macht
- [x] Danach nochmal `git add --renormalize .` ausführen ...

---

Bezieht sich auf:

- [x] Programmiermethoden/PM-Lecture
- [x] Programmiermethoden/Quizzes
- [x] ~~Programmiermethoden/Homework-Solutions~~ => wird in **Programmiermethoden/Questions** übernommen (per Git Subtree)
- [ ] Programmiermethoden/PM-Dungeon
- [x] Programmiermethoden/2021-digi-fellows

**Comment by TGrothe** [comment]
> `.gitignore`: für die im Repo tatsächlich betrachteten Dateien formulieren, nicht allgemein für "alles"

Fürs Homework-Solutions brauchen wir eigentlich nur:

```
*.class
*.jar
*.log
hs_err_pid*
.gradle/
.idea/
.metadata/   (?)
build/
reports/
```

(+ Eclipse-Sachen)

wobei class, jar und log ja eigentlich nur in den bereits ignorierten Ordnern sein sollten. hs_err_pid* tritt nur sehr selten auf, wenn die JVM mal ein Problem hat.

**Comment by cagix** [comment]
> > `.gitignore`: für die im Repo tatsächlich betrachteten Dateien formulieren, nicht allgemein für "alles"
> 
> Fürs Homework-Solutions brauchen wir eigentlich nur:
> 
> ```
> *.class
> *.jar
> *.log
> hs_err_pid*
> .gradle/
> .idea/
> .metadata/   (?)
> build/
> reports/
> ```

`.metadata/` ist von eclipse.


> 
> (+ Eclipse-Sachen)

dann schreib das doch mal bitte so auf, dass ich nicht erst noch wieder alles zusammensuchen muss. wäre echt hilfreich!

> 
> wobei class, jar und log ja eigentlich nur in den bereits ignorierten Ordnern sein sollten. hs_err_pid* tritt nur sehr selten auf, wenn die JVM mal ein Problem hat.

dito.

**Comment by TGrothe** [comment]
Das sollten alle sein (eclipse, idea und gradle):

```
hs_err_pid*
.classpath
.metadata
.project
.settings
.gradle/
.idea/
build/
reports/
target/
```

**Comment by cagix** [comment]
> Das sollten alle sein (eclipse, idea und gradle):

danke. ich hab das eben noch mit den drei java-sachen ergänzt, damit ich das später wirklich copy&paste nutzen kann und nicht erst wieder sammeln gehen muss ...

@TGrothe hatte intellij nicht noch ein file-basiertes config-file?

**Comment by TGrothe** [comment]
> @TGrothe hatte intellij nicht noch ein file-basiertes config-file?

soweit ich weiß, nicht. Das ist alles im idea Ordner.
