### ISSUE TITLE
App für Vorlesung(?)

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/PM-Lecture#605]
Vorlesungsinhalte (Webseite) als App verpacken und bereitstellen? Hintergrund: Offline-Bearbeiten der Materialien, siehe auch #56).

**Comment by AMatutat** [comment]
Wäre es nicht besser, die Webseite responsive (ist das hier das richtige Wort?) für verschiedene Endgeräte und Screensizes zu machen?
Keine Ahnung ob Hugo das kann, aber aus meiner Leien Webdeveloper Erfahrung klingt das nach dem moderneren weg.

**Comment by cagix** [comment]
@AMatutat Ja, die Webseite ist bereits responsive (glaube ich). Hier geht es eher um "offline".

**Comment by cagix** [comment]
ist ne wirre idee gewesen - closing for good :)
