### ISSUE TITLE
[VL] How to write a commit message

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/PM-Lecture#619]
Nette Ergänzung zum Einstieg in Git und Commit-Messages: [How to Write a Git Commit Message](https://cbea.ms/git-commit/)

**Comment by AMatutat** [comment]
Vielleicht mit (leicht zugekniffenen Augen) passend dazu [atomic Git commits](https://dev.to/samuelfaure/how-atomic-git-commits-dramatically-increased-my-productivity-and-will-increase-yours-too-4a84)

Idee: Jeder Commit lässt sich detailliert genug mit einem Satz beschreiben.
