### ISSUE TITLE
[Aufgaben] Dungeon-Aufgaben an neue ECS-Struktur und partielle Lösungen anpassen

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/PM-Lecture#636]
Mittlerweile haben wir im Dungeon auf ECS umgestellt. Zusätzlich existiert durch das Dungeon-Projekt eine Art Basisimplementierung für viele Dinge, die die Studis letztes Jahr noch selbst von Scratch machen mussten.

Die Aufgaben müssen alle auf den Prüfstand und ggf. angepasst werden.

- [ ] Aufgaben durchgehen:
    - [ ] Muss die Aufgabe überarbeitet werden (ECS, neue Strukturen, Aufwand/Punkte)? 
    - [ ] Muss die Aufgabe weg (zu klein/zu wenig Punkte, obsolet, ...)?
    - [ ] Kann die Aufgabe so bleiben?
    - [ ] Gibt es bereits eine Basis-Implementierung? => Code-Studium plus Erweiterung
    - [ ] Ist eine Basis-Implementierung angedacht/geplant? 
        - Offenes Ticket mit "Bounty"-Label (Links auf Suchanfrage: ["is:open is:issue label:bounty -linked:pr"](https://github.com/Programmiermethoden/Dungeon/issues?q=is%3Aopen+is%3Aissue+label%3Abounty+-linked%3Apr+)): Normal Konzept erstellen /abgeben, normal Code erstellen/abgeben => PM-Punkte. (kann also mehrere parallele Bearbeitungen geben)
        - Bis zu 5 Bonus-Punkte: Einreichen als PR, Bonus-Punkte bei Akzeptanz/Merge, nach dem Merge ist die Aufgabe für alle anderen gesperrt (Ticket geschlossen) (bei mehreren parallelen PR: nur ein Team Bonus, der Rest nur die normalen PM-Punkte) (2P bei Merge, ..3P für Verhalten und Kommunikation im PR)
        - => "Bounty-Hunter-Board" => Label "Bounty" im Dungeon, Aufgabe in PM markieren mit "Bounty"
    - [ ] Freie Aufgabe: Wie bisher aus "Spass" (nur für PM-Punkte). Bei "coolen" neuen Features oder Spielelementen oder Tests im/für Dungeon-Projekt => Bonus-Punkte (Ticket anlegen, PR einreichen, ... Vorsicht: _Kann_ abgelehnt werden!)
- [ ] Je Zyklus 15P => 5x 15P => 75P = 100% = Minimum, besser 125 Punkte bereitstellen (für Auswahl)
- [ ] Alle Aufgaben mit 5P oder 10P oder 15P
- [x] Kataloge umstrukturieren: Aufgaben nach Themen gruppieren => alte Kataloge passen
- [x] Testaufgaben bleiben drin
- [x] Freie Aufgaben bleiben drin
- [ ] Alle Aufgaben: Hinweise/Anforderung auf Lösungstechniken entfernen ("Machen Sie dies mit XYZ!": **weg**)

---

@AMatutat Ich lege das Ticket mal im PM-Lecture-Repo an, weil ich hier die ToDos bis zum Start von PM tracke. Bitte nicht nach Dungeon transferieren :)

**Comment by cagix** [comment]
> Mach ich morgen (30.12)

jetzt mach ich mir ernsthaft sorgen: welches jahr? 🤣

**Comment by AMatutat** [comment]
> Mach ich morgen (30.12)

xD Was hab ich denn da gemacht? Da stimmt ja garnix. Naja, gut ding will weile haben
