### ISSUE TITLE
[Aufgaben] Überarbeiten der Aufgabe group_basics/skill

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/PM-Lecture#647]
* [Skill Component](https://github.com/Programmiermethoden/Dungeon/tree/master/game/src/ecs/components/skill) und [System](https://github.com/Programmiermethoden/Dungeon/blob/master/game/src/ecs/systems/SkillSystem.java) ist bereits Implementiert => Code Analyse 
* Skills erstellen ist bounty 
    * Vielleicht trotzdem ein paar Skills erstellen lassen? Wenn ja, welche? 
* Diese Aufgabe mit XP Aufgabe mergen und bei level aufstieg Skills freischalten?   
* Magie sind Skills

**Comment by cagix** [comment]
fixed by #660
