### ISSUE TITLE
[Aufgaben] Überarbeiten der Aufgabe group_monster/xp

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/PM-Lecture#648]
* [XP-Component ](https://github.com/Programmiermethoden/Dungeon/tree/master/game/src/ecs/components/xp) und [System](https://github.com/Programmiermethoden/Dungeon/blob/master/game/src/ecs/systems/XPSystem.java) gibt es => Code Analyse
* Aktuell passiert beim Level UP nix => das könnte die Studis machen
    * [Stats](https://github.com/Programmiermethoden/Dungeon/tree/master/game/src/ecs/components/stats) verbessern
    * Skills freischalten  (dafür müssen die dann erst welche bauen) 
      * Aufgaben Skills erstellen und Level Up mergen (10P)?

**Comment by cagix** [comment]
fixed in #660
