### ISSUE TITLE
[Aufgaben] Überarbeiten der Aufgabe group_loot/npc

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/PM-Lecture#649]
* NPC ist nur eine Entität mit bestehenden Components => Code Analyse
* Braucht eigene AI Strategien => ist dennoch sehr Ähnlich zu der Monster Aufgabe
* Könnte der irgendwas cooles tuen? 
   * Verfolge den Spieler, aber nicht so penetrant. Geh vielleicht auch mal kurz weg und komm dann wieder und wenn der Spieler an meinen Grabstein ankommt. mach was lustiges-
* evtl. streichen und in shop/dialog integrieren?

**Comment by cagix** [comment]
fixed in #659
