### ISSUE TITLE
[Aufgaben] Überarbeiten der Aufgabe group_loot/item

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/PM-Lecture#650]
* Konzept Items gibt es schon recht ausführlich => Code Analye
* Items erstellen ist bounty => ggf. ein paar Items trotzdem hier rein? 
    * Items haben jetzt durch das SP viele Verhaltensweisen, das macht ein einzelnes item schon etwas komplexer
* Die alte Aufgabe "Taschen" lässt sich hier ggf. integrieren 

Reicht das für eine 5P Aufgabe?

**Comment by cagix** [comment]
fixed in #658
