### ISSUE TITLE
[Org] Optional nach vorne schieben

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/PM-Lecture#681]
Das Thema Optional wird im Code relativ aktiv verwendet und daher sollten die Studis so schnell wie möglich wissen wie man damit umgeht. 

Auf den ersten Blick könnte man das mit dem Thema record Klassen tauschen. Das verwenden wir zwar auch (überwiegend in den Systemen um Daten zu bündeln) aber es ist nicht so präsent und auch nicht überlebenswichtig um die ersten eigenen Inhalte zu schaffen.

**Comment by AMatutat** [comment]
@cagix ich kann dich nicht assignen, die App ist toll.

**Comment by cagix** [comment]
@AMatutat sehe ich auch so, allerdings hängt optional eng mit stream-api zusammen, ohne die streams macht optional nicht soooo viel sinn. d.h. beide müssten nach vorn ... ich schaue mir das mal an.

**Comment by cagix** [comment]
> @cagix ich kann dich nicht assignen, die App ist toll.

@AMatutat Doch, das geht schon :) ... Muss man aber irgendwo irgendwas runterwischen, und dann taucht ne Ebene mit Assignee/Project/Milestone/Label auf ...

**Comment by AMatutat** [comment]
> @AMatutat Doch, das geht schon :) ... Muss man aber irgendwo irgendwas runterwischen, und dann taucht ne Ebene mit Assignee/Project/Milestone/Label auf ...

Das hab ich gefunden aber die Nacht durfte ich nur mich assignen

**Comment by cagix** [comment]
@AMatutat Ich hab nochmal gewürfelt. Wie findest Du den neuen Entwurf:

<img width="1334" alt="Screenshot 2023-04-03 at 18 23 38" src="https://user-images.githubusercontent.com/20356276/229569891-97a6ff42-6a18-47fe-9868-9b70a7b89951.png">

**Comment by cagix** [comment]
Zur Erklärung: Optional braucht Stream als Voraussetzung, dafür brauche ich aber Methodenreferenzen und die wiederum hängen mit Lambda (und funktionale Interfaces) zusammen. Entsprechend ist das alles nach vorn gerutscht.

Records sind jetzt recht weit hinten. Man könnte ggf. noch Woche 7 und 8 vertauschen, d.h. Records vor Generics. 

What say you?

**Comment by cagix** [comment]
hmmm. man bräuchte ne musterlösung, um das mit dem optional besser sehen zu können. aber die abhängigkeit ist halt zu den anderen bausteinen da, die kriege ich kurzfristig nicht aufgelöst.

ich denke, dann tausche ich die generics nochmal mit records.
