### ISSUE TITLE
[Orga] Verlängerung der Bearbeitungszeiten und Einführen wöchentlicher "Aufgabenblätter"

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/PM-Lecture#682]
@AMatutat Ich habe die gesamte Orga auf das dieses Jahr geplante Abgabeschema umgeschrieben: 

> Das Praktikum erfolgt in 2-Wochen-Zyklen:
> 
> 1.  Erste Woche: Konzeptphase
>     -   Auswahl der zu bearbeitenden Aufgaben
>     -   Erstellung und Abgabe einer Konzeptskizze (PDF)
>     -   Peer-Feedback zur Konzeptskizze
>     -   Vorstellung der Konzeptskizze im Praktikum
> 2.  Zweite Woche: Implementierungsphase
>     -   Umsetzung des Konzepts/Implementierung der Lösung
>     -   Abgabe des Quellcodes (ZIP)
>     -   Peer-Feedback zum Quellcode
>     -   Vorstellung des Quellcodes im Praktikum
> 
> Sie können pro Zyklus Aufgaben im Umfang von 15 Punkten abgeben/vorstellen.
> 
>
> Sofern nichts anderes bei den Aufgaben angegeben ist, sind die **Lösungen jeweils bis Mittwoch 15:00 Uhr im ILIAS** hochzuladen.
> 
> Sofern nicht anders angegeben, ist das **Peer-Feedback jeweils bis Donnerstag 15:00 Uhr** im ILIAS einzutragen.

**Zwei Beobachtungen/Fragen**:

1. Das eigentlich einfache Konzept erscheint mir zunehmend komplex. Kommt mir das nur so vor oder ist das evtl. für die Studis zu komplex? Im Grunde müssen sie 6(!) Abgabeschritte machen, damit sie Punkte für einen Zyklus kriegen. Das geht doch mit Sicherheit schief, oder?

2. Mein Plan war, dass die Studis die Aufgabe bearbeiten und abgeben, sich dann gegenseitig Feedback geben und dann bis zum Praktikum nochmal etwas Zeit für eine Nachbearbeitung haben. Dadurch wird aber der Zeitplan äußerst eng: Mo-Mi eigentliche Bearbeitung, Do Feedback, Fr Praktikum. 

Siehst Du Möglichkeiten, wie wir bei dem Peer-Feedback bleiben können, ohne alles so extrem aufzublasen? 

Ich überlege, die Bearbeitung bis Do 8 Uhr zu verlängern und die Feedbackphase bis Fr 8 Uhr zu setzen. Dann verlängert sich die Bearbeitungszeit nochmal um einen Nachmittag/eine Nacht, und am Donnerstag steht nicht viel im Stundenplan, d.h. ein Peer-Feedback sollte hier zu schaffen sein (vielleicht je 3x Konzept und 1x Code). Dann bleibt bis zum Praktikum keine Zeit für Nachbearbeitung, aber das erhaltene Feedback soll ja im Praktikum besprochen werden und die Dinge können dann für die nächsten Zyklen beachtet werden. Das würde den Zeitplan etwas entzerren, aber so richtig gut gefällt mir das immer noch nicht.

Eine andere Überlegung wäre, doch wieder das Mini-Projekt rauszuholen. D.h. 5 oder 6 Wochen normaler Betrieb (jede Woche 10 Punkte ohne Peer-Feedback und ohne Konzeptskizze) und dann 4 Wochen Mini-Projekt mit Konzeptskizze und Peer-Feedback. Dann hätte ich zwar wieder zwei verschiedene Modi, aber irgendwie klingt das einfacher als die aktuelle Zyklenstruktur. Der große Nachteil ist, dass die Konzeptskizzen und das Peer-Feedback nur 1x gemacht werden und dass die Bearbeitung wg. der vier Wochen dann relativ groß wird und entsprechend blöd zu korrigieren ist.

Meinungen?

**Comment by AMatutat** [comment]
Komplex ist für mich nur das abgeben der überarbeiteten Lösung.

Ich finde die Woche für die Konzeptskizze so interessant und wichtig, dass ich eigentlich ungern darauf verzichten möchte. 

Wenn ich mich entscheiden müsste,würde ich dein Vorschlag mit der verschobenen Abgabezeit nehmen. 
Dann soll im Praktikum halt ausführlich über das Feedback gesprochen werden und das umsetzen ist dann optional. 


Das alte Konzept würde ich ungern e machen, dafür find ich die konzeptphase zu spannend.

**Comment by cagix** [comment]
Gut, dann verschiebe ich die Abgabezeiten wenigstens, damit die Studis ein wenig länger für die eigentlichen Inhalte haben und wir probieren das mit der Konzeptphase mal aus. Danke für die Beruhigung :)

Ich werde aber auf alle Fälle noch einzelne "Aufgabenblätter" machen und den Wochen zuordnen. Da steht dann zwar immer das selbe drauf (einmal für die Konzeptphase und einmal für die Implementierungsphase), aber dann ist das für die Studis einfacher zu greifen als wenn im Plan nur ein Verweis auf alle Aufgaben plus die Prüfungsmodalitäten steht.
